### ISSUE TITLE
The PMP settings page is broken on later versions of WordPress

### ISSUE THREAD

**Issue by benlk** [npr/pmp-wordpress-plugin#128]
From the "INN plugin requirements" document:

> The PMP settings page is broken on later versions of WordPress: /blog/wp-admin/admin.php?page=pmp-options-menu
> This should be fixed to be compatible up to 4.8.3

**Comment by benlk** [comment]
Do you have any specific details about how the page is broken? We were unable to reproduce an issue. 

I'm not seeing anything in https://github.com/publicmediaplatform/pmp-wordpress/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20admin that looks like this, and testing the most-recent version of the PMP plugin from wordpress.org using IPBS's credentials, I don't see any behavior that is obviously broken.

**Comment by kcalhounpmp** [comment]
Oh, I take it back. That IS INN working on the plugin. I’ll get back to them.

**Comment by petergibbons** [comment]
I am experiencing this broken settings page issue with WordPress 4.9.1 and the latest PMP plugin version installed.  
https://screencast.com/t/ZRamyFJkm

**Comment by benlk** [comment]
Updating this Issue with an email conversation back in January:

> Subject: Re: [npr/pmp-wordpress-plugin] The PMP settings page is broken on later versions of WordPress (#128)
> Date: 2018-01-22 10:33
> 
> Hi Ben,
> 
> Wanted to get back to you. We’ve had two WP instances that don’t get
> any open fields on the PMP settings page. This is the most up to date
> version of WP (4.9.2). Before I dive into making sure we can replicate
> the issue, just wanted to make sure we’re talking about the same admin
> screen. /wp-admin/admin.php?page=pmp-options-menu
> 
> Erin


> Hi Erin,
> 
> Yes, that's the page I was testing in https://github.com/npr/pmp-wordpress-plugin/issues/128
> 
> I've attached two screenshots of that page, one under WordPress 4.8.3 and one under WordPress 4.9.2. I've also attached a list of active and installed plugins as plugins.txt. The theme in use on the test site is https://github.com/INN/umbrella-ipbs/tree/master/wp-content/themes/ipbs . And when I took those screenshots, https://github.com/INN/pmp-distribution was installed and active, but even with it deactivated, the PMP settings page fields remain visible.
> 
> If visiting that page triggers server error log messages, or if there are plugins installed that might be conflicting with the pmp plugin, that would be helpful to know.
> 
> Thanks for checking,
> 
> Ben Keith

<img width="910" alt="ipbs-4 8 3" src="https://user-images.githubusercontent.com/1754187/37432897-5e327588-27b0-11e8-9d8a-44f8aeda7d86.png">
<img width="916" alt="ipbs-4 9 2" src="https://user-images.githubusercontent.com/1754187/37432898-5e425d72-27b0-11e8-857a-94c92d044a6e.png">
[plugins.txt](https://github.com/npr/pmp-wordpress-plugin/files/1813221/plugins.txt)

**Comment by benlk** [comment]
Also relevant to this PR: I'm updating the `.travis.yml` to expand test coverage to the more-recent versions of WordPress and PHP. Progress on that is in https://github.com/INN/pmp-wordpress-plugin/pull/4 with a PR against INN's fork of this repo.

**Comment by benlk** [comment]
From Erin's email:

> Ok, on the PMP credentials issues, I was just given a fresh WP install (v 4.9.4). I added PMP credentials, and set them up to use on prod, and this is what the settings page looks like now. Essentially I can’t change or reference the credentials if they disappear like this.

<img width="1305" alt="image001" src="https://user-images.githubusercontent.com/1754187/37493690-28b8eb90-287c-11e8-8bd0-54930f7bb8c4.png">

**Comment by benlk** [comment]
Server error log from Erin:

> Fatal error: Uncaught exception 'Guzzle\Common\Exception\RuntimeException' with message 'The PHP cURL extension must be installed to use Guzzle.' in /var/www/html/wp-content/plugins/public-media-platform/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php:72 Stack trace:
> #0 /var/www/html/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk/Http.php(106): Guzzle\Http\Client->__construct()
> #1 /var/www/html/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk/Http.php(47): Pmp\Sdk\Http::_buildRequest('get', 'https://api.pmp...')
> #2 /var/www/html/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk/CollectionDocJson.php(437): Pmp\Sdk\Http::bearerRequest('get', 'https://api.pmp...', NULL, NULL)
> #3 /var/www/html/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk/CollectionDocJson.php(156): Pmp\Sdk\CollectionDocJson->_request('get', 'https://api.pmp...')
> #4 /var/www/html/wp-content/plugins/public- in /var/www/html/wp-content/plugins/public-media-platform/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php on line 72

- [ ] set up a plugin dependencies check
- [ ] detect lack of curl
- [ ] deactivate and output an error message

**Comment by benlk** [comment]
PR created to fix this: https://github.com/npr/pmp-wordpress-plugin/pull/134

**Comment by benlk** [comment]
Pull request that catches this error, and displays the error message to the user: https://github.com/npr/pmp-wordpress-plugin/pull/134
