### ISSUE TITLE
It's not possible to unset the pmp_client_secret option from the interface

### ISSUE THREAD

**Issue by benlk** [npr/pmp-wordpress-plugin#130]
https://github.com/npr/pmp-wordpress-plugin/blob/master/inc/settings.php#L122-L123

The form validation logic replaces an empty value with the existing value, preventing users from ever unsetting the client secret.

```php
	if (empty($input['pmp_client_secret']) && !empty($options['pmp_client_secret']))
		$input['pmp_client_secret'] = $options['pmp_client_secret'];
```

This code is necessary because, if a client secret is saved, `pmp_client_secret_input` in its present form does not output an input containing the secret's value, but instead only outputs an anchor tag. The anchor tag has the onclick handler in https://github.com/npr/pmp-wordpress-plugin/blob/master/assets/js/pmp-options.js that replaces the anchor with an empty input, but at no point is the secret contained on the page.

**Comment by benlk** [comment]
The simple solution would be:

- put the secret in a hidden input
- remove the `if ( empty(` logic and the template
- on click, convert the hidden input to a visible input.

That approach is probably not desirable, because it sends the client secret down the wire to the browser. It certainly appears as if the PMP plugin was designed to avoid that possibility.

An alternate solution:

- add to the template:
    - a hidden input with a name something like `pmp_client_secret_reset` and a truthy value
    - a "cancel" button
    - a note saying that leaving the form blank will reset the client secret
- add a template with the "change client secret" link
- add Javascript that, if the "cancel" button is clicked, replaces the `#pmp_client_secret` form and the "cancel" button with the original "change client secret" link: this resets the form to its original state
- add to `php_settings_validate` logic:
    - if the `pmp_client_secret_reset` value is not set in the input, and if `pmp_client_secret` is not set, then the output value of `pmp_client_secret`
    - if the `pmp_client_secret_reset` value is set in the input, and if `pmp_client_secret` is empty or is not present, then the value `pmp_client_secret` is unset
    - if the `pmp_client_secret_reset` value is set in the input, and if `pmp_client_secret` is set in the input, than the new value of `pmp_client_secret` is used.
    - the value of `pmp_client_secret_reset` is never saved in the options.

**Comment by eteare** [comment]
Your alternate solution makes sense to me and now I understand why the current interface works as it does. Please go ahead and do the alt version explained above. I'd love to see the UX on this, though. We'll need pretty clear directions in the interface or in documentation. Thank you.

**Comment by benlk** [comment]
Screenshots and docs will be provided in the pull request.

**Comment by benlk** [comment]
Moving this to "Done" as we've merged https://github.com/npr/pmp-wordpress-plugin/pull/146
