### ISSUE TITLE
Release Updates

### ISSUE THREAD

**Issue by kaylima** [npr/pmp-wordpress-plugin#141]
After fixes for issues #133 and #130 are merged:

- [x] update the version number in readme.txt, plugin.php, readme.md, and other files.
- [x] review changelog and docs
- [ ] deploy an update to the plugin to WordPress.org

**Comment by benlk** [comment]
Version number was already updated to 0.2.11 in https://github.com/npr/pmp-wordpress-plugin/pull/135, but we didn't tag a release at that time because of the uncertainty around #133.

This issue isn't a duplicate, as we haven't tagged or deployed the plugin.

**Comment by benlk** [comment]
Email conversation about https://github.com/npr/pmp-wordpress-plugin/pull/152 resulted in permission to tag the release and ship it to wordpress.org.
