### ISSUE TITLE
With nonsensical settings combination, error when saving settings

### ISSUE THREAD

**Issue by benlk** [npr/pmp-wordpress-plugin#145]
This happens if:
1. You have a client ID set
2. You have no client secret set
3. You check the box to allow the PMP API to send you updates/notifications
4. You press the "submit" button.

As a result:
- In the server console:
    > PHP Warning:  Use of undefined constant REQUEST_TIME - assumed 'REQUEST_TIME' (this will throw an Error in a future version of PHP) in /sites/pmp/wp-content/plugins/public-media-platform/inc/notifications.php on line 136
- Displayed to the user as a white-page error:
    > Fatal error: Uncaught Pmp\Sdk\Exception\AuthException: [401]: Unauthorized => POST https://api.pmp.io/auth/access_token thrown in /Users/blk/sites/pmp/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk/Http.php on line 181
- The settings changes do not appear to be saved.

Ideally, before firing the request to the API to subscribe to notifications there would be a safty check, either in the plugin orin the SDK, to make sure that we have a secret that can be used to subscribe.

**Comment by eteare** [comment]
@scottsmith130 how much effort would it be to add a safety check for this in the SDK?

**Comment by scottsmith130** [comment]
Probably not much effort.  

I'm not exactly sure what the REQUEST_TIME warning has to do with this, but the AuthException already being thrown absolutely makes sense to me because if you have no client secret then certainly auth should fail.  And I think this is not just an issue for notification subscriptions, you would have this problem for any request being made.

However I do agree that catching that there is no client secret specified before making a request could be helpful (why make the request at all if you know it will fail because of that), but that is probably about as far as we could go with that (client secrets are random hashes that would be hard to predict in the SDK beyond the string length).  We'd have to be careful where we put the check though so that we don't introduce a breaking change in the SDK (perhaps we have it happen around the same place the AuthException is already thrown).

**Comment by scottsmith130** [comment]
I could also suggest that the plugin shouldn't allow an empty client secret either.

**Comment by eteare** [comment]
Let's have the PMP SDK check if the client id and secret were passed to the SDK. Scott can handle that work this week. The SDK will throw an exception.  Scott will check if this Is this the only time the AuthException is thrown. 
@benlk How do you expect the SDK to help you know that the plugin hasn't been configured? Like if the SDK gives you an AuthException could you build a message flow like the one you have built for the Story API plugin? That the plugin needs to be configured to work? Yes, that is a change order, but may be worth it.

**Comment by scottsmith130** [comment]
@benlk So I think that if we did this check in the SDK I think it would still be throwing some kind of AuthException, perhaps an extension of AuthException that is specific to missing credentials.  I think that might avoid this becoming a breaking change but still allow a client to target the specific case of missing credentials.

**Comment by benlk** [comment]
The plugin has to allow an empty client secret in the following scenarios:
- the plugin has not been configured yet.
- the plugin is no longer actively in use, but is being kept installed and activated on a site that wants to preserve some plugin functionality without access to the PMP API. (I don't know why someone would do this, but it's possible.)

If the SDK's AuthExceptions pass a message as part of the exception, the plugin can display that message. If the AuthExceptions decide to assign a specific [exception code](https://secure.php.net/manual/en/exception.getcode.php) to the case where the client secret isn't specified, the plugin can detect that that's the real reason and display a plugin-appropriate message instead of the SDK's AuthException message.

**Comment by scottsmith130** [comment]
Ok, I'll let you know what we end up doing here and also update the SDK readme accordingly.  My main concern is avoiding adding a new exception that other clients might not expect but this plan should avoid that. 

I'm not well-versed with Wordpress plugin development, but I have to ask - is it possible to force a client id/secret to be configured as part of installation of the plugin (like some kind of setup process)?  I realize its probably good to be defensive in the plugin against a id/secret being missing, but given they are important dependencies for the plugin to work, seems like it would be useful to enforce that at time of setup.

**Comment by benlk** [comment]
The plugin has a setup process, yes, but we're limited in our ability to force people to undertake it. So the plugin nags people to configure it instead.

Like I said, this issue's combination of settings is somewhat nonsensical, and I don't think it's an urgent change.

Somethings that the plugin could do here are:
- disable the notifications checkbox in clientside javascript if
    - the form element for the client ID is empty
    - the form element for the client secret exists and is empty (because if it doesn't exist, the plugin has a configured secret)
- in the settings-saving callback, if the client ID or client secret values are empty upon save, uncheck the  notifications enrollment checkbox.

**Comment by scottsmith130** [comment]
Based on how exceptions are defined and used in the SDK, and especially the AuthException in this case, and what the SDK's own readme suggests, it seems the best way to handle this without breaking changes will be to simply have an AuthException thrown if either client ID or secret are empty.  The `$code` in AuthException has in some places been set to be the HTTP status code 401 so it will be hard to establish the use of `$code` to differentiate types of auth exceptions.  We'll just need to set a different message for this and hope that no clients are actually trying to match the message.

**Comment by scottsmith130** [comment]
Should be addressed by https://github.com/npr/pmp-php-sdk/pull/41

**Comment by scottsmith130** [comment]
released v2.0.1 of the SDK with the changes
