### ISSUE TITLE
Unexpected exception when saving the settings

### ISSUE THREAD

**Issue by benlk** [npr/pmp-wordpress-plugin#151]
From https://github.com/npr/pmp-wordpress-plugin/pull/150:

> When I add client secret, id, and click "enable updates" on the settings page I get this error message above a white screen:
>
>> Fatal error: Uncaught Pmp\Sdk\Exception\AuthException: [0]: need to set the API URL, client ID, or client secret thrown in /var/www/html/wp-content/plugins/pmp-wordpress-plugin-friday-email-stuff/inc/class-sdkwrapper.php on line 20
>
> Even when we hardcoded the URL, ID and secret we still got an error message.
> See below:
>> Notice: Undefined index: pmp_client_secret in /var/www/html/wp-content/plugins/pmp-wordpress-plugin-master/inc/class-sdkwrapper.php on line 20
>> 
>> Fatal error: Uncaught Pmp\Sdk\Exception\AuthException: [0]: need to set the API URL , client ID, or client secret https://api.pmp.io thrown in /var/www/html/wp-content/plugins/pmp-wordpress-plugin-master/inc/class-sdkwrapper.php on line 20

**Comment by scottsmith130** [comment]
Ensuring the plugin is the latest from master does make the `Notice: Undefined index: pmp_client_secret...` error go away.  However the AuthException is still occurring.

Some details of the WordPress server environment:
* Wordpress 4.9.4
* PHP 5.6.37
* Percona 5.7 (database)
* Apache 2.4.25

And details of the browser attempting to save the credentials:
* Chrome 69.0.3497.100 (Official Build) (64-bit) (macOS)

I can confirm that the credentials entered in the plugin settings are being sent in the request to the `options.php` page in the WordPress site.  

I've checked the `debug.log` on the server in the WordPress site and its not giving much information beyond what is being displayed in the browser (there is no additional stack trace information).

**Comment by scottsmith130** [comment]
Another interesting find - it seems like the plugin code should be catching that `AuthException` but it isn't, the fatal error is being displayed in the browser.

**Comment by benlk** [comment]
I've never heard of Percona before, but that you're using it instead of mysql doesn't really seem relevant to this problem. I also don't think that your use of WordPress 4.9.4 versus my 4.9.8 or the tests' most-recent 4.9 (4.9.8) would be causing this problem.

The exception that's occurring is the one in the constructor for class SDKWrapper:

https://github.com/npr/pmp-wordpress-plugin/blob/0692b3280605607aa01e8e0d5b9801f9f5ac79ee/inc/class-sdkwrapper.php#L12-L28

When the AuthException occurs, can you get a detailed stack trace from the server? Setting the constants WP_DEBUG and PMP_DEBUG to true in wp-config.php might get some additional information.

Otherwise, I think we'll have to go the route I mentioned in [this comment](https://github.com/npr/pmp-wordpress-plugin/pull/150#issuecomment-427512114):

> we'd need to rewrite or review all new SDKWrapper() calls to make sure that it's only being called when the settings have been saved to the database, or to explicitly pass the settings to the wrapper so that the SDKWrapper can be called before the settings have been written to the database.

If that's the case, there's 18 cases where we'd need to make sure SDKWrapper is explicitly passed the authentication arguments:

```
$ git grep -n 'new SDKWrapper'
inc/ajax.php:14:        $sdk = new SDKWrapper();
inc/ajax.php:147:       $sdk = new SDKWrapper();
inc/ajax.php:300:       $sdk = new SDKWrapper();
inc/ajax.php:312:       $sdk = new SDKWrapper();
inc/ajax.php:325:       $sdk = new SDKWrapper();
inc/ajax.php:371:       $sdk = new SDKWrapper();
inc/class-pmppost.php:60:    $sdk = new SDKWrapper();
inc/class-pmpsyncer.php:239:    $sdk = new SDKWrapper();
inc/cron.php:52:        $sdk = new SDKWrapper();
inc/functions.php:454:  $sdk = new SDKWrapper();
inc/pages.php:72:       $sdk = new SDKWrapper();
inc/pages.php:114:      $sdk = new SDKWrapper();
inc/settings.php:133:                   $sdk = new SDKWrapper();
tests/PMPSyncerTestCase.php:31:      self::$_sdk_wrapper = new SDKWrapper();
tests/inc/test-ajax.php:13:                     $this->sdk_wrapper = new SDKWrapper();
tests/inc/test-class-sdkwrapper.php:12:                 $this->sdk_wrapper = new SDKWrapper();
tests/inc/test-cron.php:13:                     $this->sdk_wrapper = new SDKWrapper();
tests/inc/test-functions.php:13:                        $this->sdk_wrapper = new SDKWrapper();
```

The arguments would be passed either as three separate arguments ( URI, ID, secret ) or as an one argument as an associative array, which is probably faster because that's how we store it in the options field and how the data is passed around in a lot of other functions and cases.

**Comment by benlk** [comment]
A more-important question:

Does the bug happen if you first save the plugin settings with all other options filled out but not the notification checkbox checked, and then you save it with the notification checkbox checked?

If it's the case that the bug does not happen when the settings are first saved without the checkbox checked, then we can put documentation for this now for new users of the plugin, and then fix the bug in a subsequent release of the plugin.

**Comment by scottsmith130** [comment]
Persona is basically MySQL.

I'm curious if the PHP version could be relevant here. What version do you use when trying to reproduce @benlk ? 

The fact that the exception here is not being caught by the try-catch is interesting to me. Almost as if the SDKwrapper is being called somewhere else there is no try-catch.

I'd say passing the settings into the sdkwrapper does not seem difficult, that could be a solution. But if they are empty still and sdkwrapper isn't in a try-catch the exception will still cause the fatal error.

**Comment by scottsmith130** [comment]
the bug happens if saving settings the first time without the box checked. I haven't tried it myself yet with the box checked.

**Comment by benlk** [comment]
I'm using 7.2 locally, and the test suite uses 5.6, 7.0, and 7.1. But I'm not sure that we have a test that covers the save action.

I was finally able to replicate it on a completely-fresh install of WordPress, in PHP 7.2

1. Create a fresh install of WordPress
2. Install and activate the plugin
3. Go to the plugin settings page
4. Configure the plugin with a production URL, client ID, and secret. Press save
5. caught an error:
    > PHP Fatal error:  Uncaught Pmp\Sdk\Exception\AuthException: [0]: need to set the API URL, client ID, or client secret
    >
    > thrown in /wp-content/plugins/public-media-platform/inc/class-sdkwrapper.php on line 20" while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /wp-cron.php?doing_wp_cron=1539122213.8306040763854980468750 HTTP/1.1", upstream: "fastcgi://unix:/Users/blk/.valet/valet.sock:", host: "pmp.test", referrer: "http://pmp.test/wp-cron.php?doing_wp_cron=1539122213.8306040763854980468750"

I went down a quick rabbit hole to see if it was the cron task, but it was not.

<details>
<summary>Going down the rabbit hole</summary>

https://github.com/npr/pmp-wordpress-plugin/blob/4627823af54431f212612194471710a64000f1cf/inc/cron.php#L45-L52

So part of this fix is is: 

- [ ] if the list of saved search queries is empty, don't bother making a new SDKWrapper

The only place that that function is referenced is in the function that sets up the hourly cron:

https://github.com/npr/pmp-wordpress-plugin/blob/0692b3280605607aa01e8e0d5b9801f9f5ac79ee/plugin.php#L173-L185

And, importantly, it runs the cron when the plugin's options are not set.

~~If you comment out the `add_action('pmp_hourly_cron', 'pmp_hourly_cron'); ` in the plugin and rerun the test, does it still fail for you?~~

It failed for me with that commented out.

</details>

So it looks like we're going to have to audit all `new SDKWrapper` calls.

**Comment by benlk** [comment]
The exception that's giving us problems now is one added by #150, which gets thrown by the SDKWrapper when it doesn't have the necessary arguments to launch the SDK: https://github.com/npr/pmp-wordpress-plugin/pull/150/files#diff-183875a0bc7bc652e9f866ce3fae531bR20

#150 achieved its goal of preventing the SDK from throwing errors, but it looks like we've identified that the SDKWrapper was being called when it shouldn't be called, which was probably one of the places that the SDK was throwing errors in the first place.

If you put a [debug_print_backtrace](https://secure.php.net/manual/en/function.debug-print-backtrace.php) in the constructor of the SDKWrapper, after the `get_option` but before the conditional:

https://github.com/npr/pmp-wordpress-plugin/blob/0692b3280605607aa01e8e0d5b9801f9f5ac79ee/inc/class-sdkwrapper.php#L13-L15

and then rerun the tests, what does the log look like? Here's what I'm getting:

```
#0 SDKWrapper->__construct() called at [/Users/blk/sites/pmp/wp-content/plugins/public-media-platform/inc/functions.php:454] 
#1 pmp_get_my_guid() called at [/Users/blk/sites/pmp/wp-content/plugins/public-media-platform/inc/functions.php:468] 
#2 pmp_update_my_guid_transient() called at [/Users/blk/sites/pmp/wp-content/plugins/public-media-platform/inc/settings.php:301] 
#3 pmp_settings_validate(Array ([pmp_api_url] => https://api.pmp.io,[pmp_client_id] => redacted,[pmp_client_secret] => redacted)) called at [/Users/blk/sites/pmp/wp-includes/class-wp-hook.php:288] 
#4 WP_Hook->apply_filters(Array ([pmp_api_url] => https://api.pmp.io,[pmp_client_id] => redacted,[pmp_client_secret] => redacted), Array ([0] => Array ([pmp_api_url] => https://api.pmp.io,[pmp_client_id] => redacted,[pmp_client_secret] => redacted),[1] => pmp_settings,[2] => Array ([pmp_api_url] => https://api.pmp.io,[pmp_client_id] => redacted,[pmp_client_secret] => redacted))) called at [/Users/blk/sites/pmp/wp-includes/plugin.php:203] 
#5 apply_filters(sanitize_option_pmp_settings, Array ([pmp_api_url] => https://api.pmp.io,[pmp_client_id] => redacted,[pmp_client_secret] => redacted), pmp_settings, Array ([pmp_api_url] => https://api.pmp.io,[pmp_client_id] => redacted,[pmp_client_secret] => redacted)) called at [/Users/blk/sites/pmp/wp-includes/formatting.php:4314] 
#6 sanitize_option(pmp_settings, Array ([pmp_api_url] => https://api.pmp.io,[pmp_client_id] => redacted,[pmp_client_secret] => redacted)) called at [/Users/blk/sites/pmp/wp-includes/option.php:297] 
#7 update_option(pmp_settings, Array ([pmp_api_url] => https://api.pmp.io,[pmp_client_id] => redacted,[pmp_client_secret] => redacted)) called at [/Users/blk/sites/pmp/wp-admin/options.php:274] 
#8 require(/Users/blk/sites/pmp/wp-admin/options.php) called at [/Users/blk/.composer/vendor/laravel/valet/server.php:147] 
Fatal error: Uncaught Pmp\Sdk\Exception\AuthException: [0]: need to set the API URL, client ID, or client secret thrown in /Users/blk/sites/pmp/wp-content/plugins/public-media-platform/inc/class-sdkwrapper.php on line 21
```

At minimum, we'd need a try-catch in `pmp_get_my_guid` that, if caught, doesn't set the transient, but deletes the existing transient. On the other hand, that may mean that the transient never gets set during the settings load.

In conclusion, we should pass the new settings down the stack from `pmp_settings_validate` to `pmp_update_my_guid_transient` to `pmp_get_my_guid` to the SDKwrapper constructor. The SDKWrapper constructor should not be in charge of choosing the source of the settings. 

To fix this issue:

- [ ] Change SDKWrapper's constructor to accept and validate an array of arguments, or if that's not set, call `get_option()`
- [ ] every place where `new SDKWrapper` is called, pass to the SDKWrapper an array of the arguments needed to construct the SDK. In some cases, like in `pmp_settings_validate()`, the arguments passed will not come from `get_option()` but from user input.
- [ ] update the tests written for `SDKWrapper` to make sure they work with passed arguments.
- [ ] test this update using the process we've already been using to cause the problem here.

**Comment by scottsmith130** [comment]
Yes, I realize the exception is being thrown as a result of the work we did in the SDK to ensure there are credentials included.  I was just pointing out that it wasn't obvious to me why that exception wasn't being caught anywhere so that it presents the user with a nice message to go update the credentials rather than the less-than-friendly fatal error.  

I think it makes sense to explicitly give the SDKWrapper the credentials if they are already known by the plugin otherwise.  However I also think it could be nice if we catch any exception the SDKWrapper might be throwing (whether directly or indirectly via the SDK) so we can give the user a better error handling experience.

**Comment by scottsmith130** [comment]
Oh, I see the difference.  I thought the exception was the one new one being thrown by the SDK when you instantiate it.  I didn't notice that the SDKWrapper is doing the exact same thing before the SDK is even instantiated.

Either way, I think the proposed plan makes sense.  But I would still like to see if we can avoid these `AuthException` instances being presented to users as fatal errors by catching them.
